# Generated by Django 4.2.25 on 2025-10-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('artisan', 'Artisan'), ('client', 'Client'), ('agent', 'Agent'), ('admin', 'Admin')], default='client', max_length=20),
        ),
    ]
